base: base_3dcal.yaml

training:
  output_dir: /scratch/fcufino/nu_jepa/ema_patch
  checkpoint_dir: /scratch/fcufino/nu_jepa/checkpoints_ema_patch
  log_dir: /scratch/fcufino/nu_jepa/logs_ema_patch
  tensorboard_dir: /scratch/fcufino/nu_jepa/logs_ema_patch/tensorboard
